/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package act01;

import Classes.Carro_Class; // Importar classe
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 1711319
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Inserir
     */
    // Instância  de classe Carro_Class
    Carro_Class classCarro = new Carro_Class();
    List<String[]> dados = Carro_Class.lerDados("dados.txt");

    String[] opcoes = new String[dados.size()];
    String[][] opcoesSeparadas = new String[opcoes.length][6];

    String[] itemString = new String[6];
    int tamanhoOpcoes = 0;
    // String[] opcoes = {};

    public Consultar() {
        pack(); // Ajusta o tamanho do JFrame com base nos componentes
        setLocationRelativeTo(null); // Centraliza o formulário na tela
        initComponents();
        jCBCarros.removeAllItems(); // Limpa todos os itens da comboBox

        tamanhoOpcoes = opcoes.length; // Variável armazena o tamanho do array opcoes 

        // O dados recebidos devem ser tratados e armazenados.
        for (int i = 0; i < dados.size(); i++) {
            opcoes[i] = dados.get(i)[0];
            itemString = opcoes[i].split(";");
            opcoesSeparadas[i][0] = itemString[0];  // Marca
            opcoesSeparadas[i][1] = itemString[1];  // Modelo
            opcoesSeparadas[i][2] = itemString[2];  // Cor 
            opcoesSeparadas[i][3] = itemString[3];  // VelMax
            opcoesSeparadas[i][4] = itemString[4];  // VelMax
            opcoesSeparadas[i][5] = itemString[5];  // Ano

        }

        for (int i = 0; i < tamanhoOpcoes; i++) {
            jCBCarros.addItem(opcoesSeparadas[i][0] + " , " + opcoesSeparadas[i][1]);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLblConsMarca = new javax.swing.JLabel();
        jLblConsModelo = new javax.swing.JLabel();
        jLblConsAno = new javax.swing.JLabel();
        jLblConsCor = new javax.swing.JLabel();
        jLblConsVelMax = new javax.swing.JLabel();
        jBtnInserir = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnVoltar = new javax.swing.JButton();
        jBtnInsSair = new javax.swing.JButton();
        jCBCarros = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Consultar Carro");

        jLblConsMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblConsMarca.setText("Marca:");

        jLblConsModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblConsModelo.setText("Modelo:");

        jLblConsAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblConsAno.setText("Ano:");

        jLblConsCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblConsCor.setText("Cor:");

        jLblConsVelMax.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblConsVelMax.setText("Vel. Máx.");

        jBtnInserir.setText("Consultar");
        jBtnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInserirActionPerformed(evt);
            }
        });

        jBtnLimpar.setText("Limpar");
        jBtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimparActionPerformed(evt);
            }
        });

        jBtnVoltar.setText("Voltar");
        jBtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVoltarActionPerformed(evt);
            }
        });

        jBtnInsSair.setText("Sair");
        jBtnInsSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInsSairActionPerformed(evt);
            }
        });

        jCBCarros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCarrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblConsVelMax)
                    .addComponent(jLblConsCor)
                    .addComponent(jLblConsAno)
                    .addComponent(jLblConsModelo)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnInsSair))
                    .addComponent(jLblConsMarca)
                    .addComponent(jCBCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblConsMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblConsModelo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblConsAno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblConsCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblConsVelMax)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnInserir)
                    .addComponent(jBtnLimpar)
                    .addComponent(jBtnVoltar)
                    .addComponent(jBtnInsSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVoltarActionPerformed
        // TODO add your handling code here:
        Menu menuForm = new Menu(); // Instância de Menu.java
        menuForm.setVisible(true); // Tornar o menu visivel
        this.dispose(); // Descartar este formulário
    }//GEN-LAST:event_jBtnVoltarActionPerformed

    private void jBtnInsSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInsSairActionPerformed
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(this, "Quer fechar o programa?", "Confirmação", JOptionPane.YES_NO_OPTION);

        // Verifica a resposta do Utilizador
        if (resposta == JOptionPane.YES_OPTION) {
            this.dispose(); // Fecha o formulário
        }
        // Se a resposta for NO_OPTION, nada acontece e o programa continua
    }//GEN-LAST:event_jBtnInsSairActionPerformed

    private void jBtnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInserirActionPerformed
        // TODO add your handling code here:
        // Carregamento de dados de teste no formulário
        jLblConsMarca.setText("Marca: " + classCarro.obterMarcaTeste()); // Obtém marca do carro teste e atribui ao texto da etiqueta  jLblConsMarca
        jLblConsModelo.setText("Modelo: " + classCarro.obterModeloTeste());
        jLblConsAno.setText("Ano: " + classCarro.obterAnoTeste());
        jLblConsCor.setText("Cor: " + classCarro.obterCorTeste());
        jLblConsVelMax.setText("Vel. Máx.: " + classCarro.obterVelMaxTeste());

    }//GEN-LAST:event_jBtnInserirActionPerformed

    private void jBtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimparActionPerformed
        // TODO add your handling code here:
        // Limpar dados do formulário 
        jLblConsMarca.setText("Marca: ");
        jLblConsModelo.setText("Modelo: ");
        jLblConsAno.setText("Ano: ");
        jLblConsCor.setText("Cor: ");
        jLblConsVelMax.setText("Vel. Máx.: ");
    }//GEN-LAST:event_jBtnLimparActionPerformed

    private void jCBCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCarrosActionPerformed
        // TODO add your handling code here:
        // Cada iterração com a lista implica que os dados da seleção(index)
        // proporcione o carregamento dois dados de cada carro;

        for (int i = 0; i < tamanhoOpcoes; i++) {
            if (jCBCarros.getSelectedIndex() == i) {
                jLblConsMarca.setText("Marca: " + opcoesSeparadas[i][0]);
                jLblConsModelo.setText("Modelo: " + opcoesSeparadas[i][1]);
                jLblConsAno.setText("Ano: " + opcoesSeparadas[i][5]);
                jLblConsCor.setText("Cor: " + opcoesSeparadas[i][2]);
                jLblConsVelMax.setText("Vel. Max.: " + itemString[3]);
            }
        }


    }//GEN-LAST:event_jCBCarrosActionPerformed

    public static void popularCombobox(JComboBox<String> jCBCarros, List<String[]> dados) {
        for (String[] linha : dados) {
            jCBCarros.addItem(linha[0]);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Consultar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInsSair;
    private javax.swing.JButton jBtnInserir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnVoltar;
    private javax.swing.JComboBox<String> jCBCarros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblConsAno;
    private javax.swing.JLabel jLblConsCor;
    private javax.swing.JLabel jLblConsMarca;
    private javax.swing.JLabel jLblConsModelo;
    private javax.swing.JLabel jLblConsVelMax;
    // End of variables declaration//GEN-END:variables
}
